### ISSUE TITLE
Does it work on Debian (Kali)

### ISSUE THREAD

**Issue by artmus** [kovmir/l2flood#6]
I'm stuck on the make process and I thing it has to do with Kali. Is it possible to get a installation guide for Debian systems?
I installed Bluez but that also doesn't solve it. 

Cheers

**Comment by kovmir** [comment]
Does #4 help?
Also, see the [workflow file](https://github.com/kovmir/l2flood/blob/ce24d7987ecbbf69c207a0e3c3cae581e734337e/.github/workflows/build.yml#L21) to see how exactly I build it on Ubuntu.

**Comment by kovmir** [comment]
Closing due to the lack of activity, re-open if needed.
