### ISSUE TITLE
Can't connect: Host is down

### ISSUE THREAD

**Issue by Danger-Mkh** [kovmir/l2flood#8]
Hi,

I tried to run this command `sudo l2flood -t 20  BC:9F:8D:5E:C5:58`,

And i encounter this message `Can't connect: Host is down`

![image](https://github.com/user-attachments/assets/a95dfa2d-2e03-4fa0-8f4b-8eb26bb642ec)

**Comment by kovmir** [comment]
It does not look like `l2flood` issue, try to ping other devices you know are up and running, like your telephone. Try pinging both when paired and *un*paired.

**Comment by Danger-Mkh** [comment]
Thanks for advice @kovmir, your are right.

I tried and it's turns out it because devices are paired to each other, then i can't send any packet.
And when it's not paired to anything I can.
